"""added index userid, email in reminder model

Revision ID: 04c5c509063c
Revises: dae280a8d7e3
Create Date: 2024-10-29 10:54:15.452781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c5c509063c'
down_revision = 'dae280a8d7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index('reminder-idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index('reminder-idx', ['userid', 'email'], unique=False)

    # ### end Alembic commands ###
