"""added city state, faq model

Revision ID: 05934d33d0c7
Revises: e1490c48806a
Create Date: 2024-10-02 00:01:32.097871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '05934d33d0c7'
down_revision = 'e1490c48806a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('how_to_faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.drop_column('question')
        batch_op.drop_column('answer')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('thumnailurl', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('thumnailurl')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('country')
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    with op.batch_alter_table('how_to_faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('question', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
