"""added is_opt_muscians in user model

Revision ID: 0ae027078b12
Revises: 7502476507f4
Create Date: 2025-04-03 22:16:25.006710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae027078b12'
down_revision = '7502476507f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_opt_musicians', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('is_opt_musicians')

    # ### end Alembic commands ###
