"""aded index in uploaded service

Revision ID: 0be7c7b46c2c
Revises: 2716ab07c53f
Create Date: 2024-12-03 10:35:33.197757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be7c7b46c2c'
down_revision = '2716ab07c53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index('unique-service')
        batch_op.create_index('uploaded-idx', ['email', 'user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index('uploaded-idx')
        batch_op.create_index('unique-service', ['email', 'user_id'], unique=False)

    # ### end Alembic commands ###
