"""added table for contacts

Revision ID: 113af52b75a3
Revises: ba9d1c51bf35
Create Date: 2023-10-16 22:18:00.571547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113af52b75a3'
down_revision = 'ba9d1c51bf35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadedcontactfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('filepath', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploadedcontactfile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploadedcontactfile_create_datetime'), ['create_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploadedcontactfile_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_column('file_id')

    with op.batch_alter_table('uploadedcontactfile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploadedcontactfile_user_id'))
        batch_op.drop_index(batch_op.f('ix_uploadedcontactfile_create_datetime'))

    op.drop_table('uploadedcontactfile')
    # ### end Alembic commands ###
