"""added is_archived in campaign

Revision ID: 17cb8269ff09
Revises: bc1c82ee30b3
Create Date: 2025-06-27 23:24:33.006054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17cb8269ff09'
down_revision = 'bc1c82ee30b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
