"""added token column

Revision ID: 1ad83521d964
Revises: 7353c7578b02
Create Date: 2023-11-07 11:01:20.569782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad83521d964'
down_revision = '7353c7578b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unsubscribe_token', sa.String(length=128), nullable=False))
        batch_op.create_index(batch_op.f('ix_uploadedservice_unsubscribe_token'), ['unsubscribe_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploadedservice_unsubscribe_token'))
        batch_op.drop_column('unsubscribe_token')

    # ### end Alembic commands ###
