"""removed jobs table'

Revision ID: 1b1b5c66f19b
Revises: 18862550b341
Create Date: 2023-11-09 11:00:11.117108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1b5c66f19b'
down_revision = '18862550b341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler__jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler__jobs_next_run_time')

    op.drop_table('apscheduler__jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler__jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler__jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler__jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
