"""added latitude, long

Revision ID: 1fd3eb047fde
Revises: 3c3030f4aeac
Create Date: 2024-10-03 03:23:48.083218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd3eb047fde'
down_revision = '3c3030f4aeac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitute', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitute')

    # ### end Alembic commands ###
