"""added is_unsubscribed column

Revision ID: 1fd7a3a284a8
Revises: 1b1b5c66f19b
Create Date: 2023-11-09 11:03:45.143678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd7a3a284a8'
down_revision = '1b1b5c66f19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.alter_column('is_unsubscribed',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.alter_column('is_unsubscribed',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
