"""updated

Revision ID: 24d5864062fe
Revises: f3b71014cc61
Create Date: 2023-11-30 01:40:34.751209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d5864062fe'
down_revision = 'f3b71014cc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('campaignid', sa.String(length=32), nullable=True))
        batch_op.drop_index('ix_automation_contactfile_id')
        batch_op.drop_index('ix_automation_create_datetime')
        batch_op.create_index(batch_op.f('ix_automation_campaignid'), ['campaignid'], unique=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('action_id')
        batch_op.drop_column('contactfile_id')
        batch_op.drop_column('create_datetime')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('campaignid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.alter_column('campaignid',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)

    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_datetime', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('contactfile_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('action_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'action', ['action_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_automation_campaignid'))
        batch_op.create_index('ix_automation_create_datetime', ['create_datetime'], unique=False)
        batch_op.create_index('ix_automation_contactfile_id', ['contactfile_id'], unique=False)
        batch_op.drop_column('campaignid')
        batch_op.drop_column('group_count')

    # ### end Alembic commands ###
