"""updated

Revision ID: 250530bc1d36
Revises: 25b16eb53f0a
Create Date: 2023-11-11 01:00:16.344267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250530bc1d36'
down_revision = '25b16eb53f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=254),
               existing_nullable=True)
        batch_op.alter_column('product_url',
               existing_type=sa.TEXT(length=1024),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.alter_column('create_datetime',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('createddate_idx')
        batch_op.create_index(batch_op.f('ix_yelpurl_create_datetime'), ['create_datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yelpurl_create_datetime'))
        batch_op.create_index('createddate_idx', ['create_datetime'], unique=False)
        batch_op.alter_column('create_datetime',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('product_url',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(length=1024),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
