"""updated column

Revision ID: 25b16eb53f0a
Revises: fc3594d67fba
Create Date: 2023-11-10 19:02:36.753837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b16eb53f0a'
down_revision = 'fc3594d67fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index('ix_uploadedservice_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.create_index('ix_uploadedservice_email', ['email'], unique=False)

    # ### end Alembic commands ###
