"""index for reminder

Revision ID: 2716ab07c53f
Revises: 04c5c509063c
Create Date: 2024-12-02 23:24:10.171023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2716ab07c53f'
down_revision = '04c5c509063c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index('reminder-idx', ['userid', 'email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index('reminder-idx')

    # ### end Alembic commands ###
