"""updated column

Revision ID: 275e80b7ca62
Revises: e44aa30421d5
Create Date: 2023-11-10 17:40:51.504574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275e80b7ca62'
down_revision = 'e44aa30421d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.alter_column('mail_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_email_mail_id'), ['mail_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_mail_id'))
        batch_op.alter_column('mail_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
