"""added max emails per day

Revision ID: 280145b246a4
Revises: 788ed18d7f6c
Create Date: 2024-06-20 01:34:55.621084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280145b246a4'
down_revision = '788ed18d7f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_emails_per_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credit', schema=None) as batch_op:
        batch_op.drop_column('max_emails_per_day')

    # ### end Alembic commands ###
