"""add index for email in uploadedservice

Revision ID: 303cf550f112
Revises: e68f52d58491
Create Date: 2024-04-05 00:33:48.275119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303cf550f112'
down_revision = 'e68f52d58491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploadedservice_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploadedservice_email'))

    # ### end Alembic commands ###
