"""update unique constraint for Uploadedservice

Revision ID: 37cad1416fe0
Revises: 9775dba1c016
Create Date: 2025-08-20 22:40:24.278453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37cad1416fe0'
down_revision = '9775dba1c016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('bademail',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.create_unique_constraint('uploaded_service_name_email_user_id_uc', ['name', 'email', 'user_id', 'phone', 'address', 'bademail'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_constraint('uploaded_service_name_email_user_id_uc', type_='unique')
        batch_op.alter_column('bademail',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
