"""updated faq field

Revision ID: 3c3030f4aeac
Revises: 05934d33d0c7
Create Date: 2024-10-02 01:38:23.097305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c3030f4aeac'
down_revision = '05934d33d0c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('how_to_faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.LONGTEXT(), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('how_to_faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
