"""updated

Revision ID: 426fe3930272
Revises: 24d5864062fe
Create Date: 2023-11-30 01:45:31.262054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426fe3930272'
down_revision = '24d5864062fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_index('ix_campaign_campaignid')
        batch_op.drop_index('ix_campaign_contact_name')
        batch_op.drop_index('ix_campaign_create_datetime')
        batch_op.drop_index('ix_campaign_templatename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.create_index('ix_campaign_templatename', ['templatename'], unique=False)
        batch_op.create_index('ix_campaign_create_datetime', ['create_datetime'], unique=False)
        batch_op.create_index('ix_campaign_contact_name', ['contact_name'], unique=False)
        batch_op.create_index('ix_campaign_campaignid', ['campaignid'], unique=False)

    # ### end Alembic commands ###
