"""added UserCampaignSetting table

Revision ID: 4657d7eef214
Revises: 280145b246a4
Create Date: 2024-06-20 09:49:55.231734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4657d7eef214'
down_revision = '280145b246a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_campaign_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eamils_daily_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('create_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_datetime', sa.DateTime(), nullable=True))
        batch_op.drop_column('daily_limit')

    with op.batch_alter_table('user_credit', schema=None) as batch_op:
        batch_op.drop_column('max_emails_per_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_emails_per_day', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('user_campaign_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_limit', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('update_datetime')
        batch_op.drop_column('create_datetime')
        batch_op.drop_column('eamils_daily_limit')

    # ### end Alembic commands ###
