"""empty message

Revision ID: 4cbd89b145a2
Revises: 526508ac8598
Create Date: 2024-08-31 11:35:55.787833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cbd89b145a2'
down_revision = '526508ac8598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('nylas_access_token',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               type_=sa.String(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('nylas_access_token',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
