"""added is_archived in upload contact and automation

Revision ID: 4e973b9f6314
Revises: 17cb8269ff09
Create Date: 2025-07-04 18:35:53.192617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e973b9f6314'
down_revision = '17cb8269ff09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Integer(), nullable=True))

    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
