"""updated

Revision ID: 4f6abe24c79c
Revises: c05c4ac668c8
Create Date: 2023-11-30 22:03:44.081758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6abe24c79c'
down_revision = 'c05c4ac668c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.alter_column('action_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_automation_action_id'), ['action_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_action_id'))
        batch_op.alter_column('action_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
