"""updated db

Revision ID: 4fe9060e713c
Revises: 20eda6c64eeb
Create Date: 2023-11-11 17:54:34.790074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe9060e713c'
down_revision = '20eda6c64eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_job_id'))

    # ### end Alembic commands ###
