"""updated date time for yelpurl

Revision ID: 50c68d2771d6
Revises: b61e41a179f2
Create Date: 2025-06-27 01:12:54.095821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50c68d2771d6'
down_revision = 'b61e41a179f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.drop_column('update_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_datetime', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
