"""added reset password token

Revision ID: 511e61a3eb11
Revises: 4f6abe24c79c
Create Date: 2023-12-09 23:59:32.109035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511e61a3eb11'
down_revision = '4f6abe24c79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=128), nullable=True))

    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique-service', ['email', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_constraint('unique-service', type_='unique')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
