"""added nylas access token

Revision ID: 51690475ba95
Revises: 113af52b75a3
Create Date: 2023-10-20 21:37:55.902194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51690475ba95'
down_revision = '113af52b75a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nylas_access_token', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('nylas_access_token')

    # ### end Alembic commands ###
