"""update colname

Revision ID: 526508ac8598
Revises: 4657d7eef214
Create Date: 2024-06-20 11:03:07.588116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '526508ac8598'
down_revision = '4657d7eef214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_campaign_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emails_daily_limit', sa.Integer(), nullable=True))
        batch_op.drop_column('eamils_daily_limit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_campaign_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eamils_daily_limit', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('emails_daily_limit')

    # ### end Alembic commands ###
