"""add unique constraint in uploadedservice

Revision ID: 53a9d9f4a61e
Revises: e2fabb914ccf
Create Date: 2024-12-07 00:41:58.888359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53a9d9f4a61e'
down_revision = 'e2fabb914ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('venue_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=120),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.create_unique_constraint('uploaded_service_name_email_user_id_uc', ['name', 'email', 'user_id', 'phone', 'address'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_constraint('uploaded_service_name_email_user_id_uc', type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=120),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=255),
               existing_nullable=True)
        batch_op.alter_column('venue_type',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
