"""updated

Revision ID: 595ff3e27c3d
Revises: 426fe3930272
Create Date: 2023-11-30 02:45:53.556217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595ff3e27c3d'
down_revision = '426fe3930272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
