"""remove unique for username column

Revision ID: 5c347e06bf90
Revises: e848910973f6
Create Date: 2025-06-27 00:32:22.295761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c347e06bf90'
down_revision = 'e848910973f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)

    # ### end Alembic commands ###
