"""added unique in uploaded service

Revision ID: 6476d25239e6
Revises: 8ae716549a89
Create Date: 2023-11-11 22:38:31.726088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6476d25239e6'
down_revision = '8ae716549a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index('unique-service-idxemail')
        batch_op.create_unique_constraint('unique-service', ['email', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_constraint('unique-service', type_='unique')
        batch_op.create_index('unique-service-idxemail', ['user_id'], unique=False)

    # ### end Alembic commands ###
