"""added reminder, push

Revision ID: 65e351ad3a5b
Revises: 8cb44b6cddf6
Create Date: 2024-10-24 11:05:14.220132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65e351ad3a5b'
down_revision = '8cb44b6cddf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notification_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('update_datetime', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_push_notification_info_userid'), ['userid'], unique=False)

    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('venue', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('note_template', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reminder_time_utc', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reminder_reminder_time'), ['reminder_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_reminder_time_utc'), ['reminder_time_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_userid'), ['userid'], unique=False)
        batch_op.drop_column('reminder_message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_message', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_reminder_userid'))
        batch_op.drop_index(batch_op.f('ix_reminder_reminder_time_utc'))
        batch_op.drop_index(batch_op.f('ix_reminder_reminder_time'))
        batch_op.drop_column('reminder_time_utc')
        batch_op.drop_column('note_template')
        batch_op.drop_column('venue')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('note')
        batch_op.drop_column('title')

    with op.batch_alter_table('push_notification_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_notification_info_userid'))
        batch_op.drop_column('update_datetime')
        batch_op.drop_column('create_datetime')

    # ### end Alembic commands ###
