"""added 2 columns in mail

Revision ID: 67e4b5ee6630
Revises: e7a0d26b969a
Create Date: 2023-11-10 09:41:03.868429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e4b5ee6630'
down_revision = 'e7a0d26b969a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_replied', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mail_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('mail_id')
        batch_op.drop_column('is_replied')

    # ### end Alembic commands ###
