"""added index in tempid

Revision ID: 7353c7578b02
Revises: 82519dc21a8f
Create Date: 2023-11-03 11:09:53.169924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7353c7578b02'
down_revision = '82519dc21a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_tempid'), ['tempid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_tempid'))

    # ### end Alembic commands ###
