"""add biz idx

Revision ID: 7502476507f4
Revises: b584b20936c0
Create Date: 2025-04-01 00:22:53.900156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7502476507f4'
down_revision = 'b584b20936c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index('biz-idx', ['biz_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index('biz-idx')

    # ### end Alembic commands ###
