"""added new columnsin service

Revision ID: 788ed18d7f6c
Revises: 303cf550f112
Create Date: 2024-04-12 23:49:02.180730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788ed18d7f6c'
down_revision = '303cf550f112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('first_name6', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('first_name6')
        batch_op.drop_column('first_name5')
        batch_op.drop_column('first_name4')
        batch_op.drop_column('first_name3')
        batch_op.drop_column('first_name2')
        batch_op.drop_column('first_name1')

    # ### end Alembic commands ###
