"""added one column for uuid for template

Revision ID: 82519dc21a8f
Revises: 6aa73d100320
Create Date: 2023-11-03 09:30:08.427966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82519dc21a8f'
down_revision = '6aa73d100320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempid', sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_column('tempid')

    # ### end Alembic commands ###
