"""remove is allow duplication

Revision ID: 85df060357c1
Revises: 0ae027078b12
Create Date: 2025-06-21 00:58:56.404331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85df060357c1'
down_revision = '0ae027078b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('oauth_access_token')
        batch_op.drop_column('oauth_refresh_token')
        batch_op.drop_column('is_allow_duplicate')
        batch_op.drop_column('oauth_provider')
        batch_op.drop_column('oauth_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('oauth_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('is_allow_duplicate', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('oauth_refresh_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('oauth_access_token', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))

    # ### end Alembic commands ###
