"""added unique in uploaded service

Revision ID: 8ae716549a89
Revises: 4fe9060e713c
Create Date: 2023-11-11 22:30:20.662077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae716549a89'
down_revision = '4fe9060e713c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.create_index('unique-service-idxemail', ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index('unique-service-idxemail')

    # ### end Alembic commands ###
