"""added is multi

Revision ID: 8cb44b6cddf6
Revises: d4a53b52e4ce
Create Date: 2024-10-04 11:39:32.853317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb44b6cddf6'
down_revision = 'd4a53b52e4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_multi_search', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('is_multi_search')

    # ### end Alembic commands ###
