"""update reminder

Revision ID: 8fb0b7742fdb
Revises: 65e351ad3a5b
Create Date: 2024-10-24 17:29:58.757943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fb0b7742fdb'
down_revision = '65e351ad3a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_reminder_time_utc')
        batch_op.drop_column('reminder_time_utc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_time_utc', mysql.DATETIME(), nullable=True))
        batch_op.create_index('ix_reminder_reminder_time_utc', ['reminder_time_utc'], unique=False)

    # ### end Alembic commands ###
