"""added new columns in uploaded service

Revision ID: 903316d2632d
Revises: f7004eebadc7
Create Date: 2024-02-15 23:11:22.704301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903316d2632d'
down_revision = 'f7004eebadc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customtext', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('original_email', sa.String(length=255), nullable=True))

    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customtext', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('original_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_column('original_email')
        batch_op.drop_column('customtext')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('original_email')
        batch_op.drop_column('customtext')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
