"""updated db

Revision ID: 9e2448f6c6b8
Revises: ae47b257b26c
Create Date: 2023-11-28 18:50:31.370373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2448f6c6b8'
down_revision = 'ae47b257b26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_contractfile_id'), ['contractfile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_contractfile_id'))

    # ### end Alembic commands ###
