"""added is allow duplication

Revision ID: 9f37da3ef5ac
Revises: 85df060357c1
Create Date: 2025-06-21 01:00:10.628925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f37da3ef5ac'
down_revision = '85df060357c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_allow_duplicate', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('is_allow_duplicate')

    # ### end Alembic commands ###
