"""updated

Revision ID: a55aef330c37
Revises: 250530bc1d36
Create Date: 2023-11-11 01:07:36.683680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55aef330c37'
down_revision = '250530bc1d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.alter_column('userid',
               existing_type=sa.VARCHAR(length=254),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.alter_column('userid',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=254),
               existing_nullable=True)

    # ### end Alembic commands ###
