"""updated db

Revision ID: ae47b257b26c
Revises: 6476d25239e6
Create Date: 2023-11-28 18:49:04.975142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae47b257b26c'
down_revision = '6476d25239e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('contractfile_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_automation_create_datetime'), ['create_datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_create_datetime'))
        batch_op.drop_column('contractfile_id')
        batch_op.drop_column('create_datetime')

    # ### end Alembic commands ###
