"""upgraded

Revision ID: b45374f6649b
Revises: 511e61a3eb11
Create Date: 2023-12-14 18:29:40.879643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45374f6649b'
down_revision = '511e61a3eb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_column('facebook')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('website')

    # ### end Alembic commands ###
