"""updated date time for yelpurl

Revision ID: b61e41a179f2
Revises: 5c347e06bf90
Create Date: 2025-06-27 01:08:26.596767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61e41a179f2'
down_revision = '5c347e06bf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.drop_column('update_datetime')

    # ### end Alembic commands ###
