"""added new table global settings

Revision ID: b8f546375730
Revises: d20ccdaa141b
Create Date: 2024-10-29 00:08:45.994783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8f546375730'
down_revision = 'd20ccdaa141b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=191),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_reminder_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_name'))
        batch_op.alter_column('name',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
