"""init

Revision ID: ba9d1c51bf35
Revises: 
Create Date: 2023-10-14 22:19:53.912838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9d1c51bf35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('oauth_github', sa.String(length=100), nullable=True),
    sa.Column('api_token', sa.String(length=100), nullable=True),
    sa.Column('api_token_ts', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=True)

    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('venue_type', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=1024), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=1024), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('twitter', sa.String(length=255), nullable=True),
    sa.Column('email1', sa.String(length=255), nullable=True),
    sa.Column('email2', sa.String(length=255), nullable=True),
    sa.Column('email3', sa.String(length=255), nullable=True),
    sa.Column('email4', sa.String(length=255), nullable=True),
    sa.Column('fbemail1', sa.String(length=255), nullable=True),
    sa.Column('fbemail2', sa.String(length=255), nullable=True),
    sa.Column('bademail', sa.String(length=255), nullable=True),
    sa.Column('url_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('biz_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index('sevice-idx', ['url_id', 'user_id', 'biz_id'], unique=True)

    op.create_table('uploadedservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('venue_type', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_bad', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('yelpurl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=True),
    sa.Column('product_url', sa.String(length=1024), nullable=True),
    sa.Column('userid', sa.String(length=254), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yelpurl_create_datetime'), ['create_datetime'], unique=False)

    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_dance_oauth')
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yelpurl_create_datetime'))

    op.drop_table('yelpurl')
    op.drop_table('uploadedservice')
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index('sevice-idx')

    op.drop_table('service')
    op.drop_table('book')
    op.drop_table('admin')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_email'))

    op.drop_table('Users')
    # ### end Alembic commands ###
