"""added is_archived in uploadedcontact

Revision ID: bc1c82ee30b3
Revises: 50c68d2771d6
Create Date: 2025-06-27 01:54:13.653530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1c82ee30b3'
down_revision = '50c68d2771d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedcontactfile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedcontactfile', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
