"""updated

Revision ID: c05c4ac668c8
Revises: ddf557ce2559
Create Date: 2023-11-30 22:03:07.785513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05c4ac668c8'
down_revision = 'ddf557ce2559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.drop_column('action_id')

    # ### end Alembic commands ###
