"""added bademail in uploadedservice

Revision ID: cce45da8f324
Revises: 0be7c7b46c2c
Create Date: 2024-12-06 00:06:19.075009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce45da8f324'
down_revision = '0be7c7b46c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bademail', sa.String(length=255), nullable=True))
        batch_op.drop_index('uploaded-idx')
        batch_op.create_index('uploaded-idx', ['email', 'user_id'], unique=False)
        batch_op.create_index('bademail-idx', ['bademail', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploadedservice_bademail'), ['bademail'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploadedservice_bademail'))
        batch_op.drop_index('bademail-idx')
        batch_op.drop_index('uploaded-idx')
        batch_op.create_index('uploaded-idx', ['email', 'user_id'], unique=False)
        batch_op.drop_column('bademail')

    # ### end Alembic commands ###
