"""added jobid in reminder model

Revision ID: d20ccdaa141b
Revises: 8fb0b7742fdb
Create Date: 2024-10-25 10:17:55.758670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd20ccdaa141b'
down_revision = '8fb0b7742fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=191), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_reminder_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_job_id'))
        batch_op.alter_column('title',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
