"""added new columns in uploaded service

Revision ID: d33902ba93cd
Revises: 903316d2632d
Create Date: 2024-02-15 23:43:41.547537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd33902ba93cd'
down_revision = '903316d2632d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('originalemail', sa.String(length=255), nullable=True))
        batch_op.drop_column('original_email')
        batch_op.drop_column('name')

    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('originalemail', sa.String(length=255), nullable=True))
        batch_op.drop_column('original_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_email', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('originalemail')
        batch_op.drop_column('firstname')

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('original_email', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('originalemail')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
