"""update lat col name

Revision ID: d4a53b52e4ce
Revises: 1fd3eb047fde
Create Date: 2024-10-03 09:41:25.533783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4a53b52e4ce'
down_revision = '1fd3eb047fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.String(length=255), nullable=True))
        batch_op.drop_column('latitute')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yelpurl', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitute', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
