"""added index userid, email in reminder model

Revision ID: dae280a8d7e3
Revises: b8f546375730
Create Date: 2024-10-29 10:49:42.891659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae280a8d7e3'
down_revision = 'b8f546375730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.create_index('reminder-idx', ['userid', 'email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index('reminder-idx')

    # ### end Alembic commands ###
