"""added 2 tables

Revision ID: dcf7df0d781e
Revises: 1fd7a3a284a8
Create Date: 2023-11-09 18:44:47.701242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf7df0d781e'
down_revision = '1fd7a3a284a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action_id', sa.INTEGER(), nullable=False),
    sa.Column('action_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('action_datetime', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
