"""added is_bounced column

Revision ID: e1490c48806a
Revises: 4cbd89b145a2
Create Date: 2024-09-05 00:18:40.098574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1490c48806a'
down_revision = '4cbd89b145a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bounced', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('is_bounced')

    # ### end Alembic commands ###
