"""add unique constraint in uploadedservice

Revision ID: e2fabb914ccf
Revises: f93741351747
Create Date: 2024-12-07 00:31:29.962256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fabb914ccf'
down_revision = 'f93741351747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index('uploaded_service_name_email_user_id_uc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.create_index('uploaded_service_name_email_user_id_uc', ['name', 'email', 'user_id'], unique=False)

    # ### end Alembic commands ###
