"""added new emaialble table

Revision ID: e61b6d871f8b
Revises: b05a4c9606c7
Create Date: 2025-08-13 21:59:52.394348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e61b6d871f8b'
down_revision = 'b05a4c9606c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailings')
    with op.batch_alter_table('emailables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accept_all', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emailables', schema=None) as batch_op:
        batch_op.drop_column('accept_all')

    op.create_table('mailings',
    sa.Column('id', mysql.CHAR(charset='utf8mb4', collation='utf8mb4_bin', length=36), nullable=False),
    sa.Column('oauth_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('oauth_provider', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('oauth_access_token', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('oauth_refresh_token', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('appPassword', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("'1'"), nullable=True),
    sa.Column('smtp_host', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('smtp_port', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smtp_username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('smtp_password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('smtp_secure', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('smtp_require_tls', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='mailings_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
