"""added monthly credit

Revision ID: e68f52d58491
Revises: d33902ba93cd
Create Date: 2024-02-23 10:38:24.872133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68f52d58491'
down_revision = 'd33902ba93cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_credit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credit', schema=None) as batch_op:
        batch_op.drop_column('monthly_credit')

    # ### end Alembic commands ###
