"""updated db

Revision ID: e7a0d26b969a
Revises: f5b0074cb251
Create Date: 2023-11-10 04:15:56.233749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a0d26b969a'
down_revision = 'f5b0074cb251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_automation_userid'), ['userid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_userid'))
        batch_op.drop_column('userid')

    # ### end Alembic commands ###
