"""change column name for dedup

Revision ID: e848910973f6
Revises: 9f37da3ef5ac
Create Date: 2025-06-22 20:03:25.216524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e848910973f6'
down_revision = '9f37da3ef5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_allow_deduplicate', sa.Integer(), nullable=True))
        batch_op.drop_column('is_allow_duplicate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_allow_duplicate', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_allow_deduplicate')

    # ### end Alembic commands ###
