"""added bizid in 

Revision ID: e9192bc9db14
Revises: 53a9d9f4a61e
Create Date: 2025-01-28 17:46:41.136814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9192bc9db14'
down_revision = '53a9d9f4a61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_bademail'), ['bademail'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_email1'), ['email1'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_email2'), ['email2'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_email3'), ['email3'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_email4'), ['email4'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_fbemail1'), ['fbemail1'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_fbemail2'), ['fbemail2'], unique=False)

    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('biz_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_uploadedservice_biz_id'), ['biz_id'], unique=False)
        batch_op.create_index('uploaded-service-idx', ['user_id', 'biz_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index('uploaded-service-idx')
        batch_op.drop_index(batch_op.f('ix_uploadedservice_biz_id'))
        batch_op.drop_column('biz_id')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_fbemail2'))
        batch_op.drop_index(batch_op.f('ix_service_fbemail1'))
        batch_op.drop_index(batch_op.f('ix_service_email4'))
        batch_op.drop_index(batch_op.f('ix_service_email3'))
        batch_op.drop_index(batch_op.f('ix_service_email2'))
        batch_op.drop_index(batch_op.f('ix_service_email1'))
        batch_op.drop_index(batch_op.f('ix_service_bademail'))

    # ### end Alembic commands ###
