"""added isarchive in Email

Revision ID: edd96d58f9a4
Revises: 4e973b9f6314
Create Date: 2025-07-10 10:46:38.272098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd96d58f9a4'
down_revision = '4e973b9f6314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    # ### end Alembic commands ###
