"""update

Revision ID: f3b71014cc61
Revises: 9e2448f6c6b8
Create Date: 2023-11-28 21:55:39.298478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b71014cc61'
down_revision = '9e2448f6c6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contactfile_id', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_automation_contractfile_id')
        batch_op.create_index(batch_op.f('ix_automation_contactfile_id'), ['contactfile_id'], unique=False)
        batch_op.drop_column('contractfile_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contractfile_id', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_automation_contactfile_id'))
        batch_op.create_index('ix_automation_contractfile_id', ['contractfile_id'], unique=False)
        batch_op.drop_column('contactfile_id')

    # ### end Alembic commands ###
