"""removed one column

Revision ID: f5b0074cb251
Revises: dcf7df0d781e
Create Date: 2023-11-09 22:49:56.451716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b0074cb251'
down_revision = 'dcf7df0d781e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=191), nullable=True))
        batch_op.drop_column('automation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('automation_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'automation', ['automation_id'], ['id'])
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
