"""updated index

Revision ID: f7004eebadc7
Revises: a19b51d37f5b
Create Date: 2024-01-23 01:14:11.923398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7004eebadc7'
down_revision = 'a19b51d37f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploadedservice_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploadedservice_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploadedservice_phone'))
        batch_op.drop_index(batch_op.f('ix_uploadedservice_address'))

    # ### end Alembic commands ###
