"""add index in reminder

Revision ID: f93741351747
Revises: cce45da8f324
Create Date: 2024-12-06 21:15:59.594706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93741351747'
down_revision = 'cce45da8f324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index('reminder-idx')
        batch_op.create_index('reminder-idx', ['userid', 'email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.drop_index('reminder-idx')
        batch_op.create_index('reminder-idx', ['userid', 'email'], unique=False)

    # ### end Alembic commands ###
