"""updated column

Revision ID: fc3594d67fba
Revises: 2571ca1b4a93
Create Date: 2023-11-10 19:00:33.360093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3594d67fba'
down_revision = '2571ca1b4a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploadedservice_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadedservice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploadedservice_email'))

    # ### end Alembic commands ###
